version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: nurik
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
